# Generated by Django 6.0.8 on 2026-08-20 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0014_alter_academicprogram_award_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='e.g. SIWES Orientation Workshop Recording', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('VIDEO', 'Video (YouTube)'), ('DOCUMENT', 'Document / Handout'), ('WORKSHOP', 'Workshop / Seminar')], default='DOCUMENT', max_length=30)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video link (embed and thumbnail are derived from this URL)', max_length=500)),
                ('file', models.FileField(blank=True, help_text='Uploaded handout, slides, or learning document (PDF, DOCX, PPTX, TXT)', null=True, upload_to='learning_resources/%Y/%m/')),
                ('file_name', models.CharField(blank=True, help_text='Original uploaded filename', max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes')),
                ('is_published', models.BooleanField(default=True, help_text='Visible to students when checked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_resources', to='institutions.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_resources', to='institutions.academicdivision')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='institutions.institution')),
                ('session', models.ForeignKey(blank=True, help_text='Academic session this resource applies to (e.g. 2025/2026)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_resources', to='institutions.academicsession')),
            ],
            options={
                'verbose_name': 'Learning Resource',
                'verbose_name_plural': 'Learning Resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
